# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: Pull and run the container
  displayName: Pull and run the container

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # pull image
      docker pull przemekulik/nodetours:1.0

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # run container
      docker run -d --name nodetours -p 7777:7777 przemekulik/nodetours:1.0

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # call the API
      curl -I  http://localhost:7777
